# Site settings
title:       Igor Bondarenko
email:       jetmind2+blog@gmail.com
author:      Igor Bondarenko
description: "My personal blog"
baseurl:     ""
url:         "http://jetmind.github.io"

datefmt: "%Y-%m-%dT%XZ"
datedisplayfmt: "%Y, %B %-d"

# Google analytics
google_analytics: UA-47889324-1

# Social icons
github_username: jetmind
twitter_username: igrbnd
disqus_shortname: jet-techblog

# Build settings
future: true
markdown: kramdown
highlighter:  # set to 'pygments' to enable highlighting
# permalink:    pretty  # commented out to match urls from old theme
sass:
  compressed: true
