title: Igor Bondarenko
description: Igor Bondarenko
url: http://jetmind.github.io

author:
  name: Igor Bondarenko
  bio: http://jetmind.github.io

links:
  - title: GitHub
    url: https://github.com/jetmind
    external: true
  - title: Twitter
    url: https://twitter.com/igrbnd
    external: true
  - title: Feed
    url: /feed.xml

timezone: Europe/Kiev
pygments: false
markdown: redcarpet
redcarpet:
  extensions: ['smart']
