# Site settings
title:       Igor Bondarenko
email:       jetmind2+blog@gmail.com
author:      Igor Bondarenko
description: "My personal blog"
baseurl:     ""
url:         "http://jetmind.github.io"

# Google analytics
google_analytics: UA-47889324-1

# Optional features
animated:           false
show_related_posts: false
show_post_footers:  false

# Social icons
show_social_icons: true
github_username: jetmind
twitter_username: igrbnd
google_plus_id:
linkedin_username:
bitcoin_url:
paypal_url:
flattr_button:

# Build settings
markdown:     redcarpet
redcarpet:
  extensions: ['smart']
highlighter:   # set to 'pygments' to enable highlighting
#permalink:    pretty  # commented out to match urls from old theme
paginate:     5
sass:
  compressed: true
